### PR TITLE
build: Update to header 1.3.289

### PR DESCRIPTION
**Pull request by mikes-lunarg**

### CODE REVIEW

**Review by ziga-lunarg — APPROVED** [review]

**Comment by mikes-lunarg** [comment]
@charles-lunarg Looks like I need to do something similar to this: https://github.com/KhronosGroup/Vulkan-Headers/commit/e3c37e6e184a232e10b01dff5a065ce48c047f88

**Comment by charles-lunarg** [comment]
> @charles-lunarg Looks like I need to do something similar to this: [KhronosGroup/Vulkan-Headers@e3c37e6](https://github.com/KhronosGroup/Vulkan-Headers/commit/e3c37e6e184a232e10b01dff5a065ce48c047f88)

You can just set `-DVULKAN_HEADERS_ENABLE_MODULE=OFF` for the time being.

**Comment by charles-lunarg** [comment]
If its causing CI to fail across the board, maybe updating Vulkan-Headers to set module support to OFF for the time being is the better option?

**Comment by mikes-lunarg** [comment]
> If its causing CI to fail across the board, maybe updating Vulkan-Headers to set module support to OFF for the time being is the better option?

It is easy enough to opt out of modules for a while, modifying the upstream defaults is more work at this point

**Comment by charles-lunarg** [comment]
Sounds good. Frankly, its just annoying that MSVC *has* fixed the bug but its not in the runners just yet.

**Review by charles-lunarg — APPROVED** [review]

**Pull request merged**
