### PR TITLE
layer: remove VK_LAYER_SETTING_TYPE_FRAMESET_EXT

### PR DESCRIPTION
**Pull request by christophe-lunarg**

### CODE REVIEW

**Review by juan-lunarg — APPROVED** [review]
LGTM, ideally add an explanation for the change in the commit/PR message

**Comment by christophe-lunarg** [comment]
This PR will break the validation layer and the profiles layer, so I am not merging it because I created the PRs in the profiles and validation layers repositories.

**Comment by christophe-lunarg** [comment]
> LGTM, ideally add an explanation for the change in the commit/PR message

Message updated.

**Comment by christophe-lunarg** [comment]
I updated the branch with Validation layer and profiles layer. This doesn't break compatibility.

**Pull request merged**
